const a = {
  url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42',
  repository_url: 'https://api.github.com/repos/microsoft/vscode-test-web',
  labels_url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42/labels{/name}',
  comments_url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42/comments',
  events_url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42/events',
  html_url: 'https://github.com/microsoft/vscode-test-web/issues/42',
  id: 1380782203,
  node_id: 'I_kwDOFx3e7s5STRB7',
  number: 42,
  title: 'How to start with https?',
  user: {
    login: 'yiliang114',
    id: 11473889,
    node_id: 'MDQ6VXNlcjExNDczODg5',
    avatar_url: 'https://avatars.githubusercontent.com/u/11473889?v=4',
    gravatar_id: '',
    url: 'https://api.github.com/users/yiliang114',
    html_url: 'https://github.com/yiliang114',
    followers_url: 'https://api.github.com/users/yiliang114/followers',
    following_url: 'https://api.github.com/users/yiliang114/following{/other_user}',
    gists_url: 'https://api.github.com/users/yiliang114/gists{/gist_id}',
    starred_url: 'https://api.github.com/users/yiliang114/starred{/owner}{/repo}',
    subscriptions_url: 'https://api.github.com/users/yiliang114/subscriptions',
    organizations_url: 'https://api.github.com/users/yiliang114/orgs',
    repos_url: 'https://api.github.com/users/yiliang114/repos',
    events_url: 'https://api.github.com/users/yiliang114/events{/privacy}',
    received_events_url: 'https://api.github.com/users/yiliang114/received_events',
    type: 'User',
    site_admin: false,
  },
  labels: [],
  state: 'open',
  locked: false,
  assignee: null,
  assignees: [],
  milestone: null,
  comments: 0,
  created_at: '2022-09-21T11:35:34Z',
  updated_at: '2023-06-16T03:18:26Z',
  closed_at: null,
  author_association: 'NONE',
  active_lock_reason: null,
  body:
    '[https://github.com/microsoft/vscode-test-web/blob/main/src/server/app.ts#L20](https://github.com/microsoft/vscode-test-web/blob/main/src/server/app.ts#L20) \r\n' +
    '\r\n' +
    'As can be seen from this, only http is supported by default, and no ssl entry is reserved? \n' +
    '```[tasklist]\n' +
    '### Tasks\n' +
    '```\n',
  reactions: {
    url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42/reactions',
    total_count: 0,
    '+1': 0,
    '-1': 0,
    laugh: 0,
    hooray: 0,
    confused: 0,
    heart: 0,
    rocket: 0,
    eyes: 0,
  },
  timeline_url: 'https://api.github.com/repos/microsoft/vscode-test-web/issues/42/timeline',
  performed_via_github_app: null,
  state_reason: null,
};
