name: GitHub - Activity - Readme
description: Updates README with the recent GitHub activity of a user
author: yiliang114

inputs:
  GH_REPOS: # 输入项名称
    description: "Your care repos" # 描述
    default: ${{ github.event.repository.name }} # 默认值
    required: false # 是否是必填项
  GH_USERNAMES:
    description: "Your GitHub username"
    default: ${{ github.repository_owner }} # group or user
    required: false
  COMMIT_NAME:
    description: "Name of the committer"
    default: "github-actions[bot]"
    required: false
  COMMIT_EMAIL:
    description: "Email of the committer"
    default: "41898282+github-actions[bot]@users.noreply.github.com"
    required: false
  COMMIT_MSG:
    description: "Commit message used while committing to the repo"
    default: ":zap: Update README with the recent activity"
    required: false
  MAX_LINES:
    description: "The maximum number of lines populated in your readme file"
    default: 10
    required: false
  TARGET_FILE:
    description: "The file location to write changes to"
    default: "README.md"
    required: false
branding:
  color: yellow
  icon: activity

runs:
  using: node16
  main: ./dist/index.js
