name: Dev test

on:
  push:
    branches: [dev]

jobs:
  test:
    name: test ./index.js
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Cache NPM dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('./pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-
      - uses: pnpm/action-setup@v2.2.4
        with:
          version: 7.1.0
      - name: Install NPM dependencies
        run: pnpm i --frozen-lockfile --ignore-scripts
      - name: Code Style Check
        run: pnpm run format:check
      - name: Build
        run: pnpm run build
      # 检查是否有变化
      - name: Compare the expected and actual dist/ directories
        run: |
          if [ "$(git diff --ignore-space-at-eol dist/ | wc -l)" -gt "0" ]; then
            echo "Detected uncommitted changes after build.  See status below:"
            git diff
            exit 1
          fi
        id: diff
      # If index.js was different than expected, then perform test tasks
      - name: Commit Build dist/ directory
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git commit -m "[skip actions] build(dist): update dist/ directory" -a
          git push origin HEAD:${{ github.ref }}
      # If index.js was different than expected, then perform test tasks
      - uses: ./
        if: ${{ failure() && steps.diff.conclusion == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          GH_USERNAMES: "yiliang114, harbin1053020115"
          GH_REPOS: "microsoft/vscode, microsoft/vscode-l10n, microsoft/vscode-test-web, coder/code-server"
